### PR TITLE
fix: convert `samples` argument in `Genotypes.read` into a set and fix `tr_harmonizer` bug arising when TRTools is also installed

### PR DESCRIPTION
**Pull request by mlamkin7**
Added lazy option to all Genotypes Classes which when false (default) sorts output genotypes in the same order as the list of samples given (if given). 

Also updated tr_harmonizer dependency so it won't error when TRTools is installed.

### CODE REVIEW

**Review by aryarm — COMMENTED** [review]
A couple ideas:
1. Now that I'm thinking about it, naming it `lazy` might be confusing since `lazy` is also a parameter of cyvcf2 and people might think that this is that parameter. What do you think about calling it something like `reorder_samples` and defaulting it to True?
2. Can you add type hints? So `lazy=False` would become `lazy: bool = False`, for example
3. The Genotypes classes also have an `__iter__()` method that is supposed to work similarly to the `read()` method except it's supposed to read things line by line to reduce memory-use. Unfortunately, we won't be able to use `subset()` to reorder samples for that. What should we do in that case, do you think? I'd prefer the behavior of `__iter__()` to continue to align with `read()` as much as possible

**Comment by aryarm** [comment]
I just thought of something that might be potentially super important, @mlamkin7 and @gymreklab .

According to the numpy docs, `Genotypes.subset()` will trigger a copy of the entire genotype matrix to be made in memory because we have to use advanced indexing to reorder the columns of the genotype matrix:

> Advanced indexing always returns a copy of the data
https://numpy.org/doc/stable/user/basics.indexing.html

So we should probably check that this code doesn't double the amount of memory of `read()`. I can look into a way to check that.

**Comment by mlamkin7** [comment]
> A couple ideas:
> 
> 1. Now that I'm thinking about it, naming it `lazy` might be confusing since `lazy` is also a parameter of `cyvcf2` and people might think that this is that parameter. What do you think about calling it something like `reorder_samples` and defaulting it to True?
> 2. Can you add type hints to be consistent? So `lazy=False` would become `lazy: bool = False`, for example
> 3. The Genotypes classes also have an `__iter__()` method that is supposed to work similarly to the `read()` method except it's supposed to read things line by line to reduce memory-use. Unfortunately, we won't be able to use `subset()` to reorder samples for that. What should we do in that case, do you think? I'd prefer the behavior of `__iter__()` to continue to align with `read()` as much as possible

Updated 1. and 2., but 3 does pose an issue since I believe it returns one variant at a time? we may have to sort each time.

**Review by aryarm — COMMENTED** [review]
the readthedocs build is failing because the type hints refer to cyvcf2, but it isn't imported

changing `cyvcf2.VCF` to `VCF` should fix that

**Comment by aryarm** [comment]
Confirming now that running `subset()` together with `read()` does indeed double the peak memory usage :(

### results
Running `read()` and then `subset()` gives us a peak memory usage of 8.8 MiB. Judging by the intensity (in color) of the flamegraph bars for the `read()` and `subset()` functions, roughly half of the 8.8 MiB is due to `read()` while the other half is due to `subset()`.
peak-memory
Running just `read()` alone gives us a peak memory usage of 5.1 MiB. Most of this is due to the initial allocation of memory for the genotype matrix by `read()`.
peak-memory
For more info on how to interpret the flamegraphs, take a look at [the filprofiler docs](https://pythonspeed.com/fil/docs/interpreting-output.html)

### reproducing this
in case we need it for later, here are the steps to reproduce this
Using commit 56dddf46b193f38e23cf40809745873f4031bdb7, run this command
```bash
fil-profile run tests/bench_genotypes_mem.py
```
with this script
```python
#!/usr/bin/env python

from filprofiler.api import profile

from haptools.data import GenotypesPLINK

gt = GenotypesPLINK("../happler/tests/data/19_45401409-46401409_1000G.pgen", chunk_size=1)
gt2 = GenotypesPLINK("../happler/tests/data/19_45401409-46401409_1000G.pgen", chunk_size=1)

def read():
    gt.read()

def read_and_subset():
    gt2.read()
    gt2.subset(samples=gt2.samples, inplace=True)

profile(read, "fil-result/bench_read_GenotypesPLINK")
profile(read_and_subset, "fil-result/bench_read_subset_GenotypesPLINK")
```
using [this file](
https://github.com/gymrek-lab/happler/blob/7876136ff78f9f98d7e3da07db708fb234bf9db9/tests/data/19_45401409-46401409_1000G.pgen)

**Review by aryarm — APPROVED** [review]
Tests passed! 🚀

**Pull request merged**
