### PR TITLE
fix: 1) improve error in `transform` when providing an empty hap file and a `--region` and 2) allow for calling `write()` on Genotypes objects without variants

### PR DESCRIPTION
**Pull request by aryarm**
This PR fixes two issues.

## 1. An issue with the `transform` command

When the input `.hap` file is empty and the `--region` parameter is provided, the `transform` command will fail with cryptic `psyam` errors instead of outputting an empty genotypes file. This PR resolves those.

The first error occurs with a regular hap file (that isn't indexed):
```
OSError: index `empty.hap.tbi` not found
```
https://github.com/CAST-genomics/haptools/actions/runs/12058438776/job/33625133365#step:9:380

And the second occurs when the hap file is indexed:
```
ValueError: could not create iterator for region '1:10116-10122'
```
https://github.com/CAST-genomics/haptools/actions/runs/12058465901/job/33625213549#step:9:400

## 2. An issue with the Genotypes classes

As an extra bonus, this PR also resolves an error in the `GenotypesVCF` and `GenotypesPLINK` classes when attempting to write files without any variants:
```
OSError: [Errno 9] Bad file descriptor
```
and
```
RuntimeError: b'No variants in test.pvar.\n'
```
https://github.com/CAST-genomics/haptools/actions/runs/12059160422/job/33627254672#step:9:378

### CODE REVIEW

**Comment by aryarm** [comment]
@mlamkin7, what do you think about this? Is the correct behavior to write an empty file or should we error out instead?

It gets a little weird for the PGEN files. For those, I think the `pgenlib` won't even let me write an empty PGEN file, so I just write an empty file, instead. Not sure if that's a good idea, though...

**Comment by mlamkin7** [comment]
> @mlamkin7, what do you think about this? Is the correct behavior to write an empty file or should we error out instead?
> 
> It gets a little weird for the PGEN files. For those, I think the `pgenlib` library won't even let me write an empty PGEN file, so I just manually write an empty file, instead. Not sure if that's a good idea, though...

Right now I can't think of any reason why transform would happen with an empty hap file and we would want an empty output. I'd say its better just to error out and let them know .hap is empty.

**Comment by aryarm** [comment]
ok, that sounds reasonable

I'll add some code to raise those errors

**Comment by aryarm** [comment]
ok, done! See 525fd4463fa1bfe3099819ee015d27267ad0d455 for the new Value Error in `transform`

Note that I also made some minor changes in 98898330dd9cf5c412e50740cbe9065097048b89 to unrelated things:
I integrated our project with VSCode in the `.devcontainer.json` file, and VSCode pointed out a few missing import statements and complained about some type-hints

If you want to view the changes in this PR without the minor changes in 98898330dd9cf5c412e50740cbe9065097048b89, click [here](https://github.com/CAST-genomics/haptools/compare/16a84d1..525fd44)

**Review by mlamkin7 — APPROVED** [review]

**Pull request merged**
